config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#landing_page'
  get 'static_pages/index'
  get 'static_pages/about'
  get 'static_pages/contact'
  post 'static_pages/thank_you'
  post 'payments/create'

devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => { :registrations => "user_registrations"}
resources :users

resources :products do 
  resources :comments
end 

resources :orders, only: [:index, :show, :create, :destroy]

end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :orders
	has_many :comments
validates :name, presence: true

def average_rating
  	comments.average(:rating).to_f
end

 def total_rating
    comments.count(:rating).to_f
 end	
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  #before_filter :authenticate_user!
  respond_to :json, :html

  # GET /products
  # GET /products.json
  def index
    if params[:q]
    search_term = params[:q]
    @products = Product.where("name LIKE ?", "%#{search_term}%")
  else
    @products = Product.all
    end
    respond_with @products
  end 

  # GET /products/1
  # GET /products/1.json
  def show
    # Interactive debugging 6.9 exercise
    # byebug
    @comments = @product.comments.order("created_at DESC").paginate(page: params[:page], per_page: 3)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count          = Product.count
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

app/views/products/_comments.html.erb
<div class="container-fluid">

	<div class="product-reviews">
	<% @comments.each do |comment| %>
		<div class="row">
			<hr>
			<p>
				<%= comment.user.first_name %>  <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
				<% if signed_in? && current_user.admin? %>
					<%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(@product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
				<% end %>
			</p>
		<div class="rated" data-score="<%= comment.rating %>"></div>
			<p><%= comment.body %></p>
		</div><!--end row --> 
	<% end %>
</div>

<div class="pagination">
    <div class="page_info">
      <%= page_entries_info @comments %>
    </div>
    <%= will_paginate @comments, :container => false %>
  </div>

</div><!-- /container-fluid -->

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
  <%= f.label :colour %><br>
  <%= f.text_field :colour %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_new_comment.html.erb
<% if signed_in? %>

  <h4>Add a review:</h4>
  <%= form_for([@product, @product.comments.build], remote: true) do |f| %>

    <p>
      <%= f.label :body, "Comments" %><br>
      <%= f.text_area :body %>
    </p>

    <p>
      <div class="rating"></div>
    </p>

    <p>
      <%= f.submit "Submit" %>
    </p>
  <% end %>

<% end %>

app/views/products/_product.html.erb
<div class="col-xs-12 col-sm-6 col-lg-4"> 
	
	<div class="thumbnail">
		<%= image_tag(product.image_url, class: "img-responsive") %> 
	</div><!--thumbnail --> 

	<div class="col-sm-6 col-md-9">
		<% cache product do %>
		<h3><%= link_to product.name, product %></h3>
		<p><b>Product Description:</b> <%= product.description %></p>
		<p><b>Colour:</b> <%= product.colour %></p> 
		<span class="lead">Price <%= number_to_currency(product.price) %></span>
		
		<hr>

  		<%= link_to 'Edit', edit_product_path(product), class: "btn btn-warning" %> 
  		<%= link_to 'Back', products_path , class: "btn btn-info" %>
  		<%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-danger"%>
  		<% end %>
	</div><!--col sm-6 col-md-9 --> 
	
	</div><!--col --> 
	

app/views/products/edit.html.erb
<div class="container"> 
<h1>Edit Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>
</div>

app/views/products/index.html.erb
<div class= "container">
	<h2> Shoe Products </h2> 
		<% cache(cache_key_for_products) do %>
		<%= render @products %>
		<% end %>
<br> 
	<%= link_to 'New Product', new_product_path %>
</div> 

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<% cache @product do %>
<div class="container"> 

<%= link_to 'Edit', edit_product_path(@product), class: "btn btn-success", role: "button" %> |
<%= link_to 'Back', products_path, class: "btn btn-success", role: "button" %>

<div class="row">
  <% cache @product do %>
  <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
    <%= image_tag(@product.image_url, width: "250", class: "img-responsive img-zoom", data_zoom_image: @product.image_url) %>
 
  </div> <!-- end col-md-8--> 

   <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
    <p><h2><%= @product.name %></h2></p>
    <p><%= @product.description %></p>
    <strong>Price:</strong>
      <p> <%= number_to_currency(@product.price) %></p>
    <p><strong>Colour:</strong> <%= @product.colour %></p>
    <strong>Average Rating:</strong>
    <p><div class="rated", data-score="<%= @product.average_rating %>"></div></p>

    <!-- Stripe payment button -->
      <%= form_tag "/payments/create" do %>
        <%= render partial: "shared/stripe_checkout_button" %>
        <%= hidden_field_tag(:product_id, @product.id) %> 
      <% end %>
</div> <!-- end col-md-4--> 
<% end %>  <!-- cache product -->  
</div> <!-- end row --> 

<% end %>
<%= render 'new_comment' %>

<%= render 'comments' %>

</div> <!--end container --> 