config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#landing_page'
  get 'static_pages/index'
  get 'static_pages/about'
  get 'static_pages/contact'
  post 'static_pages/thank_you'
  post 'payments/create'

devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => { :registrations => "user_registrations"}
resources :users

resources :products do 
  resources :comments
end 

resources :orders, only: [:index, :show, :create, :destroy]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nicolaapp</title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>

<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <span class= "navbar-brand"><%= link_to "Brand",  'http://www.nike.com/us/en_us/c/running/nike-run-club/training-plans' %>
        </span> 
    </div> <!-- end navbar-header -->

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", static_pages_index_path %></li>
        <li><%= link_to "About", static_pages_about_path %></li>
        <li><%= link_to "Products", products_path %></li>
        <li><%= link_to "Contact", static_pages_contact_path %></li>

        <% if user_signed_in? %>
          <li>
            <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
          </li>
            <% else %>
          <li>
           <%= link_to('Login', new_user_session_path) %> 
          </li>
          <% end %>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          
          <ul class="dropdown-menu">
            <li><a href="#">Example Action</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "New Product", new_product_path %></li>
            <li role="separator" class="divider"></li>
          
          </ul> <!-- end dropdown-menu -->
        </li> <!-- end dropdown -->
      </ul> <!-- end nav navbar-nav -->

    
    <!-- Search box -->
        <%= form_tag("/products", method: "get", class: "navbar-form navbar-right") do %>
          <div class="form-group"> 
            <%= label_tag(:q, "Search for:", class: "hidden") %>
            <%= text_field_tag(:q, "", class: "search-box", placeholder: "Search for") %>
            <%= submit_tag("Submit", class: "search-btn btn btn-default") %>
          </div> <!-- end form-group -->
        <% end %>

    </div><!-- end navbar-collapse -->
  </div><!-- end container-fluid -->
</nav> <!-- end navbar navbar-default --> 

  <div class="messages"> 
    <% if notice %> 
      <p id="notice" class= "alert alert-info"><%= notice %></p>
    <% end %>

    <% if alert %> 
      <p id="alert" class= "alert alert-warning"><%= alert %></p>
    <% end %>
  </div> <!-- end messages -->

<%= yield %>

	<footer class="app footer">
		&copy; 2016 Nicola App
    <br>
    Date and local time is <%= Time.now %>
	</footer> 

</body>
</html>